# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b6278f417bff976abd3dd2ea98d9f30b53680f6263413673536b9d45de11418e4feeebc0c5e413f356e1bcccddd5ad365f9b535f25a9d2ca8aedbfaa8219c7cf

test:
  secret_key_base: 22199ed5421991d44d48e426f54e8b082ead92448363783f1d6edea8d8f8e7a4f7511b49d9acf84d73fdd957178dc9b66edd43d30ac42a69f08d53a42f742837

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
